### ISSUE TITLE
purging endpoints that are also h2 pushed

### ISSUE THREAD

**Issue by mlue** [fastly/fastly-ruby#149]
Has anyone else had inconsistent results when purging when using this gem. The server response is 'OK' as though the request had succeeded, but the url is not purged. This is hard to reproduce because the gem sometimes works for this url, but purging using a `curl -XPURGE` from the commandline always work. The url has the following headers for what it's worth

```
         response.headers["Cache-Control"] = "max-age=600, public"
         response.headers["Surrogate-Control"] = "max-age=315360000, stale-if-error=86400"
``` 
for what it's worth.

Purging our other assets via this gem is never an issue, only this one. The only difference between this and our other assets is that we H2 push this.

**Comment by thommahoney** [comment]
Hey @mlue this is a great question that I don't know the answer to, but I'm sure our support team would be able to provide an answer. If we find that this is an issue with this library, do report back. In the meantime, you can reach our support team by emailing support@fastly.com.

Thanks!
