### ISSUE TITLE
Run rubocop on this gem and fix issues

### ISSUE THREAD

**Issue by annawinkler** [fastly/fastly-ruby#157]
Run rubocop and fix the issues.

**Comment by gschorkopf** [comment]
@annawinkler what if we use https://github.com/testdouble/standard instead?

**Comment by annawinkler** [comment]
@gschorkopf Yes, I think that would be great to use Standard - thank you for the suggestion!

**Comment by mmrobins** [comment]
FWIW +1 to using `standardrb` instead of just `rubocop`.  `rubocop` is overbearing in its opinions, and I found the rubocop warnings in the current code annoying when trying to make a small fix.

**Comment by Integralist** [comment]
Closing this issue now we've published v4.0.0 https://rubygems.org/gems/fastly
