### ISSUE TITLE
Add a pull request template

### ISSUE THREAD

**Issue by gschorkopf** [fastly/fastly-ruby#161]
Adding a file in the path `.github/PULL_REQUEST_TEMPLATE.md` will allow us to have uniform pull requests. Some thoughts on what to put there:

* What issue is this resolving?
* Any particular things to focus on for review?
* What kind of version bump (if any) does this require?

**Comment by annawinkler** [comment]
I appreciate the addition of a feels giphy when people feel so inclined ✨

**Comment by Integralist** [comment]
Closing this issue now we've published v4.0.0 https://rubygems.org/gems/fastly
