### ISSUE TITLE
Add code climate / coveralls

### ISSUE THREAD

**Issue by gschorkopf** [fastly/fastly-ruby#164]
https://codeclimate.com/
https://github.com/lemurheavy/coveralls-ruby

Let's ensure our code is up to par, and that our test coverage is robust. Open to other options, these are just the tools I've used before.

**Comment by annawinkler** [comment]
💯 Great idea! I've used codeclimate before and I like it.

**Comment by Integralist** [comment]
Closing this issue now we've published v4.0.0 https://rubygems.org/gems/fastly
