### ISSUE TITLE
Cleanup admin-only functionality

### ISSUE THREAD

**Issue by mmay** [fastly/fastly-ruby#39]
From discussion in https://github.com/fastly/fastly-ruby/pull/38

I say kill the `set_customer` method since it can only be used by Fastly Admins and I'm of the opinion that we shouldn't muck up our "public" clients with special-for-fastly-use-only hacks.

**Comment by Integralist** [comment]
Closing this issue now we've published v4.0.0 https://rubygems.org/gems/fastly
