### ISSUE TITLE
When chaining methods to purge by surrogate key, get_service API call is executed every time

### ISSUE THREAD

**Issue by kigster** [fastly/fastly-ruby#50]
We needed to purge objects by a surrogate key, and had the code shown in the image below (red). We were instantiating ```Fastly.new``` object, then calling ```get_service()```, and then chaining ```purge_by_key(key)```. This usage ends up calling an API to get service every time for each purge, and we ended up exceeding rate limits for the API.

The solution is shown in green, and should probably be documented somewhere. Perhaps another class ```Purge``` should take care of executing these calls efficiently, given that all keys and api_keys are known ahead of time.

![Diff that got rid of an extra get_service API call to Fastly per purge](https://cloud.githubusercontent.com/assets/259982/7642597/27cb29d4-fa47-11e4-8c9a-cfa8c90ee5b5.jpg)

**Comment by drbrain** [comment]
@kigster how does #51 look to you?
