### ISSUE TITLE
Does purge_by_key require more then API_KEY to work?

### ISSUE THREAD

**Issue by briancox730** [fastly/fastly-ruby#52]
Following the implementation on the readme I provided the API_KEY and SERVICE_ID as ENV variables. When I try to purge by key I get error unauthorized. Do I need username/password as well and did I miss those instructions somewhere? Running a rails app and hosting data via S3.

As a follow up why would I need username/password if I have API KEY?

fastly  = Fastly.new(api_key: 'YOUR_API_KEY')
service = Fastly::Service.new({ id: 'YOUR_SERVICE_ID' }, fastly)

service.purge_by_key("/key")

**Comment by briancox730** [comment]
Using these lines works from my local machine but does not work on the EC2 box hosting the app.

Thanks for any help you can offer!

**Comment by set5think** [comment]
Hi,

regarding api key authentication vs username/password, api key authentication allows access to a subset of actions that a user has.  Username/password (aka session) authentication grants you access to all the actions that your user role would allow you to do.  Visit docs.fastly.com, and you'll notice that the API reference states which type of authentication you need for the various API calls.

Can you provide the error you're getting from your hosted app on EC2?

**Comment by briancox730** [comment]
Unauthorized 
severity=ERROR, /usr/local/rvm/gems/ruby-2.0.0-p598/gems/fastly-1.1.5/lib/fastly/client.rb:95:in `post_and_put' 
severity=ERROR, /usr/local/rvm/gems/ruby-2.0.0-p598/gems/fastly-1.1.5/lib/fastly/client.rb:74:in `post' 
severity=ERROR, /usr/local/rvm/gems/ruby-2.0.0-p598/gems/fastly-1.1.5/lib/fastly/service.rb:70:in `purge_by_key'

**Comment by briancox730** [comment]
fastly = Fastly.new(api_key: ENV['FASTLY_API_KEY'])
service = Fastly::Service.new({id: ENV['FASTLY_SERVICE_ID']}, fastly)
service.purge_by_key("/containers/#{@placement.id}")

This is what I have written in a publish controller action.

**Comment by mmay** [comment]
Hi,

I tried running the above exactly and I couldn't replication the problem on my end - I get 200 OKs back. The `Unauthorized` response message makes me think that you're using the wrong api key or it's not correctly set up as an env var on your ec2 box.

Hope that helps

**Comment by briancox730** [comment]
Alright it was a problem with how we deployed our ENV keys thanks for your help!
