### ISSUE TITLE
Purge by key returns status 200 but purge does not seem to fire

### ISSUE THREAD

**Issue by briancox730** [fastly/fastly-ruby#54]
```
    begin
      fastly = Fastly.new(api_key: ENV['FASTLY_API_KEY'])
      service = Fastly::Service.new({id: ENV['FASTLY_SERVICE_ID']}, fastly)
      response = service.purge_by_key("/containers/#{@placement.id}")

      flash[:notice] = "Purge Success! - response: #{response["status"]}, id: #{response["id"]}"
    rescue Exception => e
      Rails.logger.error("A fastly error has occured! #{e}")
      e.backtrace.each { |line| Rails.logger.error line }
      flash[:notice] = "Container ID = #{@placement.id} - Purge failure! Purge manually"
    end
```

First is that the proper way to use purge_by_key? Or should it be full URL?
Second:
   I tried using the normal dashboard purge and tried to purge a URL I knew was not a valid URL for our CDN but it still returns a status 200 with a purge id. So is there any checking for if the URL is valid or does this 200 status not mean what I think it means? Maybe it just means that I successfully sent the request regardless of what happens afterwards?

**Comment by jondade** [comment]
Brian, This is actually the proper behaviour from our API. A 200 response means that we accepted the purge request. There is no checking if there was content to purge. If there was we removed it and if not then there wasn't content to remove. Either way its gone now. :)
