### ISSUE TITLE
regexp should be regex

### ISSUE THREAD

**Issue by cthorner** [fastly/fastly-ruby#64]
create_header is not recognizing the 'regexp' attribute when creating a header
```
fastly.create_header(service_id: 123412341234, version: 42, name: 'MyHeader, type: 'request',
                                   action: 'regex',
                                   dst: 'url',
                                   src: 'req.url',
                                   regexp: '^/some(regexpthisvalueisnotset)?/',
                                   substitution: "/somenewvaluethisoneworks/",
                                   ignore_if_set: 0,
                                   priority: 10
)
```

This creates the header for service with id 123412341234, but the value for "match" is blank. 

Dropping the "p" at the end of the regexp attribute works better:

```
regex: '^/some(regexpthisvalueisnotset)?/',
```

it doesn't make sense, because in the code it clearly states that it should be regexp. Here:
https://github.com/fastly/fastly-ruby/blob/master/lib/fastly/header.rb#L57
and attr_accessor definition here:
https://github.com/fastly/fastly-ruby/blob/master/lib/fastly/header.rb#L4

Suggested fix would be to switch attr_accessor to regex instead of regexp.

**Comment by thommahoney** [comment]
Thank you for identifying this problem! Addressing this issue here: https://github.com/fastly/fastly-ruby/pull/68
