### ISSUE TITLE
Initializing Fastly.new with api_key option fails  on version 1.2.2

### ISSUE THREAD

**Issue by cthomaspdx** [fastly/fastly-ruby#73]
Fastly.new({api_key: '''})
NameError: uninitialized constant Fastly::Client::OpenSSL
	from /Users/thomas/.chefdk/gem/ruby/2.1.0/gems/fastly-1.2.2/lib/fastly/client.rb:21:in `initialize'
	from /Users/thomas/.chefdk/gem/ruby/2.1.0/gems/fastly-1.2.2/lib/fastly/fetcher.rb:19:in `new'
	from /Users/thomas/.chefdk/gem/ruby/2.1.0/gems/fastly-1.2.2/lib/fastly/fetcher.rb:19:in `client'
	from /Users/thomas/.chefdk/gem/ruby/2.1.0/gems/fastly-1.2.2/lib/fastly.rb:48:in `initialize'
	from (irb):3:in `new'
	from (irb):3
	from /opt/chefdk/embedded/bin/irb:11:in `<main>'

**Comment by cthomaspdx** [comment]
Here is a fix. https://github.com/fastly/fastly-ruby/pull/72

**Comment by thommahoney** [comment]
I released version 1.2.3 which includes your fix.
